name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Github Packages

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      
      - name: Publish
        run: npm publish
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}